apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: developer-side-code
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - nodePort: 30002 
      port: 80
      targetPort: 80
