apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service 
  namespace: developer-side-code
spec:
  type: ClusterIP 
  selector:
    app: devc
  ports:
    - port: 80    
      targetPort: 5000 
