apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service
  namespace:  developer-side-code
spec:
  type: NodePort
  selector:
    app: devc
  ports:
    - nodePort: 30001
      port: 80
      targetPort: 5000
